services:
  app:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health_monitor_bot
    restart: unless-stopped
    volumes:
      - ./app/logs:/app/logs
      - ./app/measurements.db:/app/measurements.db
    environment:
      - TOKEN=${TOKEN}
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org/bot${TOKEN}/getMe', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
