services:
  app:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health_monitor_bot
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - app-logs:/app/logs
      - app-data:/app/data
    environment:
      - TOKEN=${TOKEN}
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org/bot${TOKEN}/getMe', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app-data:
  app-logs:
