services:
  app:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    container_name: bot_app
  
    command: >
      sh -c "python main.py"
