name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Download source tarball (no external actions)
        env:
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          curl -sSL -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${REPO}/tarball/${SHA} -o source.tar.gz
          mkdir src
          tar -xzf source.tar.gz -C src --strip-components=1

      - name: Show Python version
        run: python3 -V
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        working-directory: src
        run: |
          uv sync  --dev
      - name: Run tests
        working-directory: src
        run: python3 -m pytest -q

